-- =============================================================
-- Script  : gold_layer.sql
-- Layer   : Gold
-- Author  : thonne
-- Date    : 2026-04-26
-- =============================================================
-- Purpose:
--   Creates the Gold layer views that form the star schema
--   for analytical consumption. Gold is built on top of
--   cleaned and typed Silver tables.
--
--   Star schema structure:
--     fact_sales      ← central fact table
--     dim_customers   ← customer dimension (CRM + ERP)
--     dim_products    ← product dimension (CRM + ERP category)
--
--   All Gold objects are VIEWS — they query Silver on demand
--   and always reflect the latest Silver data without needing
--   a separate load step.
--
-- Usage:
--   Run this script once after silver_load.sql has been
--   executed. Views are live — no reload needed.
--   To refresh data: CALL silver.load_silver()
--
-- Dependencies:
--   - init_database.sql         (gold schema must exist)
--   - silver/silver_load.sql    (silver tables must be loaded)
--
-- Execution order:
--   1. gold.dim_customers       (no dependencies)
--   2. gold.dim_products        (no dependencies)
--   3. gold.fact_sales          (depends on dim_customers, dim_products)
-- =============================================================


-- -------------------------------------------------------------
-- DIMENSION: gold.dim_customers
-- -------------------------------------------------------------
-- Purpose:
--   Conformed customer dimension integrating three Silver
--   sources into one flat denormalised table:
--     - silver.crm_cust_info   → core customer attributes
--     - silver.erp_loc_a101    → country / location data
--     - silver.erp_cust_az12   → birth date and gender supplement
--
--   Gender logic: CRM is the primary source. ERP fills the
--   gap only when CRM gender is UNKNOWN.
--
--   Surrogate key: ROW_NUMBER() ordered by cst_id.
--   Natural keys:  customer_id (cst_id), customer_number (cst_key)
--                  are preserved for traceability.
--
--   Join strategy: LEFT JOINs ensure no customer is lost
--   even if ERP location or ERP customer data is missing.
-- -------------------------------------------------------------

DROP VIEW IF EXISTS gold.dim_customers;

CREATE VIEW gold.dim_customers AS
SELECT
    -- surrogate key — unique integer generated by warehouse
    -- ROW_NUMBER guarantees no duplicates, no gaps
    ROW_NUMBER() OVER (ORDER BY ci.cst_id)  AS customer_key,

    -- natural keys — preserved for traceability and source joins
    ci.cst_id                               AS customer_id,
    ci.cst_key                              AS customer_number,

    -- customer attributes from CRM
    ci.cst_firstname                        AS first_name,
    ci.cst_lastname                         AS last_name,
    ci.cst_marital_status                   AS marital_status,
    ci.cst_create_date                      AS create_date,

    -- location from ERP — NULL if no matching ERP record
    ela.cntry                               AS country,

    -- gender: CRM is primary source, ERP fills gap
    -- if CRM knows the gender use it, otherwise try ERP
    CASE
        WHEN ci.cst_gndr != 'UNKNOWN' THEN ci.cst_gndr
        ELSE COALESCE(eca.gen, 'UNKNOWN')
    END                                     AS gender,

    -- birth date from ERP customer supplement
    eca.bdate                               AS birthdate

FROM silver.crm_cust_info AS ci

-- enrich with country from ERP location table
-- LEFT JOIN: customers without location record still appear
LEFT JOIN silver.erp_loc_a101 ela
    ON ci.cst_key = ela.cid

-- enrich with birth date and gender from ERP customer table
-- LEFT JOIN: customers without ERP record still appear
LEFT JOIN silver.erp_cust_az12 eca
    ON ci.cst_key = eca.cid;


-- -------------------------------------------------------------
-- DIMENSION: gold.dim_products
-- -------------------------------------------------------------
-- Purpose:
--   Product dimension integrating two Silver sources:
--     - silver.crm_prd_info      → core product attributes
--     - silver.erp_px_cat_g1v2   → category and subcategory
--
--   Only CURRENT product versions are included in Gold.
--   Historical versions (prd_end_dt != '9999-12-31') are
--   filtered out — they exist in Silver for audit purposes
--   but analysts only need current products in the dimension.
--
--   Surrogate key: ROW_NUMBER() ordered by prd_start_dt, prd_key
--   to ensure deterministic ordering across product versions.
--
--   Join: cat_id in crm_prd_info was derived from the first
--   5 characters of prd_key (with hyphen replaced by underscore)
--   and matches the id column in erp_px_cat_g1v2.
-- -------------------------------------------------------------

DROP VIEW IF EXISTS gold.dim_products;

CREATE VIEW gold.dim_products AS
SELECT
    -- surrogate key
    ROW_NUMBER() OVER (
        ORDER BY cpi.prd_start_dt, cpi.prd_key
    )                                       AS product_key,

    -- natural keys preserved
    cpi.prd_id                              AS product_id,
    cpi.prd_key                             AS product_number,
    cpi.cat_id                              AS category_id,

    -- product attributes from CRM
    cpi.prd_nm                              AS product_name,
    cpi.prd_cost                            AS cost,
    cpi.prd_line                            AS product_line,
    cpi.prd_start_dt                        AS start_date,

    -- category attributes from ERP category table
    -- NULL if no matching category record
    pc.cat                                  AS category,
    pc.subcat                               AS subcategory,
    pc.maintenance                          AS maintenance

FROM silver.crm_prd_info AS cpi

-- enrich with category and subcategory from ERP
-- LEFT JOIN: products without category still appear
LEFT JOIN silver.erp_px_cat_g1v2 AS pc
    ON cpi.cat_id = pc.id

-- only include currently active product versions
-- prd_end_dt = '9999-12-31' is the SCD2 sentinel for active
-- historical versions are kept in Silver for audit only
WHERE cpi.prd_end_dt = '9999-12-31';


-- -------------------------------------------------------------
-- FACT TABLE: gold.fact_sales
-- -------------------------------------------------------------
-- Purpose:
--   Central fact table of the star schema. Records individual
--   sales transactions with foreign keys to both dimensions.
--
--   Grain: one row = one sales order line.
--
--   Measures: sales_amount, quantity, price
--   These are additive — safe to SUM across any dimension.
--
--   Foreign keys:
--     product_key → gold.dim_products.product_key
--     customer_key → gold.dim_customers.customer_key
--
--   Join strategy: LEFT JOINs preserve all sales transactions
--   even if a product or customer has no matching dimension
--   record. NULL keys in the result signal referential
--   integrity issues to investigate.
--
--   Source: silver.crm_sales_details
--   The fact table does not store descriptive attributes —
--   those are resolved at query time through dimension joins.
-- -------------------------------------------------------------

DROP VIEW IF EXISTS gold.fact_sales;

CREATE VIEW gold.fact_sales AS
SELECT
    -- degenerate dimension — order number has no dimension table
    -- kept directly on the fact for order-level filtering
    sd.sls_ord_num                          AS order_number,

    -- foreign keys linking to dimensions
    -- NULL here means no matching dim record — investigate
    dp.product_key,
    dc.customer_key,

    -- date measures — stored as dates, join to dim_date if needed
    sd.sls_order_dt                         AS order_date,
    sd.sls_ship_dt                          AS shipping_date,
    sd.sls_due_dt                           AS due_date,

    -- additive numeric measures
    -- safe to SUM, AVG, COUNT across any dimension slice
    sd.sls_sales                            AS sales_amount,
    sd.sls_quantity                         AS quantity,
    sd.sls_price                            AS price

FROM silver.crm_sales_details AS sd

-- resolve product surrogate key from product number
LEFT JOIN gold.dim_products AS dp
    ON sd.sls_prd_key = dp.product_number

-- resolve customer surrogate key from customer id
LEFT JOIN gold.dim_customers AS dc
    ON sd.sls_cust_id = dc.customer_id;